### ISSUE TITLE
New release after 2.1

### ISSUE THREAD

**Issue by ncraike** [pyradius/pyrad#106]
Hi,

Would it be possible to ship a new release of `pyrad` to PyPI and similar? Is there anything I can do to help ship a new release?

There's a few changes and bugfixes since the 2.1 release which it would be great to have in an easy-to-install version. Particularly at the moment, change e8feefcb, but I can see other changes to `pyrad/server.py` and other issues closed since the 2.1 release in February 2017.

**Comment by mnach** [comment]
Hi!
I would like to have new release too.. Or at least, understand what to do to bring it closer
May be we

**Comment by GIC-de** [comment]
@wichert we should look for/add additional maintainers?

**Comment by wichert** [comment]
@GIC-de I certainly can't hurt. Personally I haven't done anything with RADIUS in a long long time by now, so I am no longer the right person to maintain it.

I suggest is that we also move pyrad out of my personal GitHub account into a pyrad organisation, and find 2 or 3 people to maintain it.

**Comment by GIC-de** [comment]
@wichert moving pyrad to an own organization would be great and makes it easier to add maintainers to the project.

**Comment by wichert** [comment]
Unfortunately  it seems the name `pyrad` is already taken. Does anyone have suggestions for another name?

**Comment by GIC-de** [comment]
I would suggest `pyradius/pyrad`

**Comment by wichert** [comment]
I have created the organisation, and invited @GIC-de to be an owner.

**Comment by worlvlhole** [comment]
@GIC-de  Do you have any plans on making a new release?

**Comment by GIC-de** [comment]
Version 2.2 released!
