### ISSUE TITLE
Dictionary attribute integer conversion failures

### ISSUE THREAD

**Issue by morrowc** [pyradius/pyrad#119]
Ran into some failures in testing pyrad:
....
pyrad/dictionary.py", line 228, in __ParseAttribute
    code = int(codes[0])
ValueError: invalid literal for int() with base 10: '0x0700'
...

This appears to be a 'simple' case to fix, providing PR shortly.

**Comment by Istvan91** [comment]
PR accepted, fixed in: https://github.com/pyradius/pyrad/tree/8ebd46c3502a10831c2248bb27028794cf728f28
