### ISSUE TITLE
(Examples) A bit of confussion resolving local addresses 

### ISSUE THREAD

**Issue by pvilas** [pyradius/pyrad#122]
Hi,

I know this is not exactly a pyrad issue but I would suggest that in both `server.py`and `auth.py` examples the host would be `127.0.0.1` and the server bind to `0.0.0.0`.  It possibly make easier to try pyrad.

A link to the readthedocs on the project README.md would be useful too.

**Comment by GIC-de** [comment]
Thanks for your feedback. I updated the examples but there is already a link in README.md to readthedocs (see doc label).
