### ISSUE TITLE
Support for passwords > 16 characters long

### ISSUE THREAD

**Issue by jtanios** [pyradius/pyrad#130]
Is there a reason why the server only supports [passwords 16 characters or less](https://github.com/pyradius/pyrad/blob/master/pyrad/packet.py#L680)? I did a quick search and didn't find a password limit in the RADIUS protocol definition.

**Comment by Istvan91** [comment]
Have you tested it to not work with more than 16 characters?

The password gets (pseudo)hashed down to 16 characters (regardless of how long it actually is). The algorithm is described in https://tools.ietf.org/html/rfc2865#section-5.2 .

**Comment by Istvan91** [comment]
Did this answer your question?

**Comment by jtanios** [comment]
@Istvan91, yes, thank you!

The 16 char limit turned out to be a limitation on the RADIUS client used.
