### ISSUE TITLE
Unknown column 'acctupdatetime' 

### ISSUE THREAD

**Issue by monelgordillo** [pyradius/pyrad#133]
I'm getting this from the radius side, when I run acct.py:

(25) sql: ERROR: rlm_sql_mysql: ERROR 1054 (Unknown column 'acctupdatetime' in 'field list'): 42S22

**Comment by Istvan91** [comment]
This looks like you're running freeradius on the server side. I can't help you much with that. At first glance it looks like: http://freeradius.1045715.n5.nabble.com/quot-acctupdatetime-quot-missing-in-the-radacct-table-accounting-failure-td5754705.html

**Comment by monelgordillo** [comment]
Yes, that was it.  Thank you.
