### ISSUE TITLE
Missing send_packet for async client ?

### ISSUE THREAD

**Issue by MikhailMS** [pyradius/pyrad#135]
Is it just me, or there are 2 lines of code missing [here](https://github.com/pyradius/pyrad/blob/master/pyrad/client_async.py#L399) and [here](https://github.com/pyradius/pyrad/blob/master/pyrad/client_async.py#L403) to allow async client to send acct and coa packets ?

I've seen a PR about it, but it's not been merged into master

**Comment by Istvan91** [comment]
That is correct, it is missing and not yet included... I'll take care of it

**Comment by Istvan91** [comment]
Done, if there is no follow up, I'll close this ticket soon

**Comment by MikhailMS** [comment]
That was fast :)

Thank you very much and thanks for making this package - really useful :)
