### ISSUE TITLE
Unknown chars in server reply

### ISSUE THREAD

**Issue by mapolone** [pyradius/pyrad#141]
Hello,
I'm using pyrad in order to test access on a couple of FreeRadius servers. On the first one, quite out-of-date indeed (I can retrieve the exact version if needed) this is the reply I get:

```
Sending authentication request
Access accepted
Attributes returned by server:
235: ['\x00\x00\x00\n']
Framed-IP-Address: ['redacted']
(529, 228): ['\x00\x00\x00\x01']
Framed-IP-Netmask: ['255.255.255.255']
Framed-Routing: ['None']
Service-Type: ['Framed-User']
Framed-Protocol: ['PPP']
Framed-MTU: [1500]
(529, 135): ['\xd4a \x02']
(529, 136): ['^\x8d\x18\\']
```

while on the new one no problem at all.
[Here](https://gist.github.com/mapolone/3ac1646e4b5dd7d41f7bb740103c00df) the script I'm using for test.

**Comment by Istvan91** [comment]
This means those attributes are not in the radius dictionary.

235 looks like one of the Ascend-Attributes.
I've got no idea which vendor 529 is.

I think the easiest way would be to copy the dictionaries from the freeradius server and use them.

**Comment by mapolone** [comment]
Thank you, issue can be closed.
