### ISSUE TITLE
New version request

### ISSUE THREAD

**Issue by pallas** [pyradius/pyrad#142]
There have been a good number of fixes since the release in February. I'd like to politely request a new release tag & PyPI upload if it's not too much trouble. If there are more issues that need to be closed before that happens, let me know and I'm happy to take a look.

**Comment by GIC-de** [comment]
Sorry for the delay but here it is :-) 

I automated the PyPI upload using GitHub actions planning to release more frequent.

**Comment by pallas** [comment]
Awesome, thanks, & no worries :)
