### ISSUE TITLE
 can't open file 'file_name.py': [Errno 2 ] No such file or directory

### ISSUE THREAD

**Issue by hayasalman** [pyradius/pyrad#154]
~/OneDrive/python
$ python first_script.py
C:/Users/user3/anaconda3/python.exe: **can't open file 'file_name.py': [Errno 2] No such file or directory**

whenever I tried to run the script on my machine I got this Error , So please help me solve it.

**Comment by GIC-de** [comment]
This issue is not related to pyradius/pyrad!
