### ISSUE TITLE
Round Robin with several radius servers

### ISSUE THREAD

**Issue by cornelinux** [pyradius/pyrad#69]
Are there any plans to support round robin in the client request?

When creating a client, I could pass the RADIUS server list, assuming that both RADIUS servers have the same secret and port

<pre>
srv = Client(server=[server1, server2],
                    authport=port,
                     secret=decryptPassword(secret),
                     dict=Dictionary(r_dict))
</pre>

Then it would be no problem to create the Auth Package:

<pre>
req = srv.CreateAuthPacket(code=pyrad.packet.AccessRequest,
                                   User_Name=user.encode('ascii'),
                                   NAS_Identifier=nas_identifier.encode('ascii'))
req["User-Password"] = req.PwCrypt(password)
</pre>

And send the request:

    response = srv.SendPacket(req)

How could I assist?

**Comment by rbricheno** [comment]
It isn't integrated into pyrad, but I implemented a version of this here:

https://github.com/rbricheno/client_of_redundant_servers/blob/master/client_of_redundant_servers/client_of_redundant_radius_servers.py

**Comment by GIC-de** [comment]
Not in scope of this project.
